#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LegendsOfClassicalMusic.Resource", IsApplication=true)]

namespace LegendsOfClassicalMusic
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f040000
			public const int inanim = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int outanim = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int zoomexit1 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int zoomexit2 = 2130968579;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int black = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int defaultcolor = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int pressedcolor = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int white = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int app_bg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Bach = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Beethoven = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Brahms = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Chopin = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Debussy = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int debut_dark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Handel = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Haydn = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int layout_selector = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Mendelssohn = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Mozart = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Rachmaninoff = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Rossini = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Tchaikovsky = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Verdi = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Vivaldi = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Wagner = 2130837522;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070006
			public const int biographyText = 2131165190;
			
			// aapt resource value: 0x7f07000b
			public const int composerAge = 2131165195;
			
			// aapt resource value: 0x7f070003
			public const int composerEra = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int composerImage = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int composerName = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int composerNationality = 2131165188;
			
			// aapt resource value: 0x7f070008
			public const int famousWork = 2131165192;
			
			// aapt resource value: 0x7f07000c
			public const int gridview = 2131165196;
			
			// aapt resource value: 0x7f070005
			public const int labelBiography = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int labelFamousWork = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int labelYouTubeFamousWork = 2131165193;
			
			// aapt resource value: 0x7f070000
			public const int titleBar = 2131165184;
			
			// aapt resource value: 0x7f07000a
			public const int youtubeWebView = 2131165194;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int composer_detail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int home_menu_list_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
